laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('contacts', function() {
	return view('contacts.contacts');
});
//Route::get('order', 'OrdersController@show')->name('orders.order');
Route::resource('table', 'ReservationTableController', ['only'=>['create', 'store']]);
Route::get('orders/store', 'OrdersController@store')->name('orders.store');

Route::group(['middleware' => ['auth', 'isAdmin']], function () {
    Route::resource('users', 'UserCheck');
    Route::resource('meniu', 'MeniuListController', ['except'=>['index', 'show']]);
    Route::resource('orders', 'OrdersController', ['except'=>['index', 'show', 'store']]);
    Route::resource('table', 'ReservationTableController', ['except'=>['create', 'store']]);
});

Route::group(['middleware' => ['auth']], function () {
    Route::resource('user', 'UserEdit');
    Route::resource('cart', 'ShoppingCart');
    Route::resource('orders', 'OrdersController', ['only'=>['index', 'show', 'store']]);
    Route::put('user', 'UserEdit@update')->name('user.update');
});

Route::resource('meniu', 'MeniuListController', ['only'=>['index', 'show']]);
Auth::routes();
Route::get('/home', 'HomeController@index');

laravel/app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\User;
use App\Product;

class Order extends Model
{
    protected $fillable = [
        'user_id', 'total',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function products()
    {
        return $this->belongsToMany(Product::class);
    }

    public function productOrders()
    {
        return $this->hasMany(ProductOrder::class);
    }
}

laravel/app/Http/Controllers/OrdersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Order;
use \App\ProductOrder;
use \App\User;
use Illuminate\Support\Facades\Auth;

class OrdersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::user()->admin == 1)
        $order = Order::all();
        else
        $order = Auth::user()->orders;


        return view('orders.orders', compact('order'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $order = New Order();
        $total = \App\Cart::totalBrutto();
        $products = \App\Cart::getProducts();
        $cart = \App\Cart::get();

        $order->user_id = Auth::user()->id;
        $order->total = $total;
        $order->save();

        foreach ($products as $product)
        {
            $order->products()->attach($product->id, ['price'=>$product->price, 'quantity' => $cart[$product->id]]);
        }

        $request->session()->forget('cart');

        // isvalyt is sesijos krepseli
        // peradresuoti useri i uzsakymu sarasa
//        return redirect('orders.index', compact('order'));
        return redirect()  ->route('orders.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        $order = Order::find($id);
        $products = $order -> productOrders;


        return view('orders.order')->with( compact('products', 'order'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

laravel/resources/views/orders/order.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default">
            <div class="panel-body">
                <table class="table table-hover">
                    <tr>
                        <th>Order ID:</th>
                        <th>User_ID:</th>
                        <th>Total:</th>
                    </tr>
                    <tr>
                        <td>{{ $order->id }}</td>
                        <td>{{ $order->user_id }}</td>
                        <td>{{ $order->total }}</td>
                    </tr>
                </table>
                <table class="table table-hover">
                    <tr>
                        <th>Product ID:</th>
                        <th>Order ID:</th>
                        <th>Quantity:</th>
                    </tr>
                    @foreach($products as $product)
                    <tr>
                        <td>{{ $product->id }}</td>
                        <td>{{ $product->order_id }}</td>
                        <td>{{ $product->quantity }}</td>
                    </tr>
                    @endforeach
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

laravel/resources/views/orders/orders.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default">
            <div class="panel-body">
                <table class="table table-hover">
                    <tr>
                        <th>Order ID:</th>
                        <th>User ID:</th>
                        <th>Total price:</th>
                    </tr>
                    @foreach ($order as $one)
                        <tr style="cursor:pointer" onclick="window.location.href ='{{ route('orders.show', $one->id) }}';">
                            <td>{{ $one->id }}</td>
                            <td>{{ $one->user_id }}</td>
                            <td>{{ $one->total }}</td>
                        </tr>
                    @endforeach
                </table>
            </div>
        </div>
    </div>
</div>


@endsection