laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('contacts', function() {
	return view('contacts.contacts');
});
//Route::get('order', 'OrdersController@show')->name('orders.order');
Route::resource('table', 'ReservationTableController', ['only'=>['create', 'store']]);
Route::get('orders/store', 'OrdersController@store')->name('orders.store');

Route::group(['middleware' => ['auth', 'isAdmin']], function () {
    Route::resource('users', 'UserCheck');
    Route::resource('meniu', 'MeniuListController', ['except'=>['index', 'show']]);
    Route::resource('orders', 'OrdersController', ['except'=>['index', 'show', 'store']]);
    Route::resource('table', 'ReservationTableController', ['except'=>['create', 'store']]);
});

Route::group(['middleware' => ['auth']], function () {
    Route::resource('user', 'UserEdit');
    Route::resource('cart', 'ShoppingCart');
    Route::resource('orders', 'OrdersController', ['only'=>['index', 'show', 'store']]);
    Route::put('user', 'UserEdit@update')->name('user.update');
});

Route::resource('meniu', 'MeniuListController', ['only'=>['index', 'show']]);
Auth::routes();
Route::get('/home', 'HomeController@index');

laravel/app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ['name','description','price', 'image'];

    public function getPriceNetto()
    {

    	return $this->price * 1.21;
    }
}

laravel/resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-md-12">
         <a href="/meniu"><button>To meniu list:</button></a>
    </div>
</div>
<div>
    @foreach ($errors->all() as $message)
        <div class="alert alert-danger">
            {{$message}}
        </div>
    @endforeach
    {!! Form::open(array('route' => 'meniu.store', 'files' => true)) !!}
        <strong>Product:</strong>
        {!! Form::text('name', '',['class' => 'form-control']) !!}
        <strong>Description:</strong>
        {!! Form::text('description', '',['class' => 'form-control']) !!}
        <strong>Price without VAT:</strong>
        {!! Form::text('price', '',['class' => 'form-control']) !!}
        <strong>Image:</strong>
        {!! Form::file('image',['class' => 'form-control']) !!}
        <button type="submit">Submit</button>
    {!! Form::close() !!}
</div>
@endsection

laravel/resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-md-12">
        <a href="/meniu"><button>To meniu list:</button></a>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-body">
                @foreach ($errors->all() as $message)
                    <div class="alert-danger">
                        {{$message}}
                    </div>
                @endforeach
                {{--{!! Form::open(array('route' => 'meniu.update', 'files' => true)) !!}--}}
                {!! Form::model($product, array('method' => 'PUT', 'url' => route('meniu.update',  ['meniu' => $product->id]), 'files' => true)) !!}
                    <strong>Product:</strong>
                    {!! Form::text('name', $product->product,['class' => 'form-control']) !!}
                    <strong>Description:</strong>
                    {!! Form::text('description', $product->description,['class' => 'form-control']) !!}
                    <strong>Price:</strong>
                    {!! Form::text('price', $product->price,['class' => 'form-control']) !!}
                    <img src="{{ Storage::url($product->image) }}">
                    {!! Form::file('image')!!}
                    <button type="submit">Submit</button>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

laravel/resources/views/products/meniu.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-md-12">
        <!-- @if (Auth::check())
        <a href="/cart"><button>Cart:</button></a>
        @endif -->
        @if(Auth::check() && Auth::user()->isAdmin())
            <a href="/meniu/create"><button>Create new item:</button></a>
        @endif
    </div>
</div>
@if(Auth::check() && Auth::user()->isAdmin())
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table table-hover">
                        <tr>
                            <th>Product:</th>
                            <th>Description:</th>
                            <th>Price:</th>
                            <th>Image:</th>
                        </tr>
                        @foreach ($products as $product)
                            <tr style="cursor:pointer" onclick="window.location.href ='{{ route('meniu.show', $product->id) }}';">
                                <td>{{ $product->name }}</td>
                                <td>{{ $product->description }}</td>
                                <td>{{ $product->price }}</td>
                                <td>@if($product->image == null)
                                        <span>[Nuotraukos nera]</span>
                                    @else
                                        <img src="{{ Storage::url($product->image) }}" alt="" style="max-width: 300px;">
                                    @endif
                                </td>
                                <td>
                                    <button>
                                        <a href="{{ route('meniu.edit', $product->id) }}">edit</a>
                                    </button>
                                    <div>
                                        {!! Form::open([
                                            'method' => 'DELETE',
                                            'route' => ['meniu.destroy', $product->id]
                                        ]) !!}
                                        {!! Form::submit('delete', ['class' => 'button']) !!}
                                        {!! Form::close() !!}
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </table>
                </div>
            </div>
        </div>
    </div>
        @else
    <div class="row">
        <div class="col-sm-12">
        @foreach ($products as $product)
            <a href="{{ route('meniu.show', $product->id) }}" class="col-lg-4 col-md-6 col-sm-12">
                <div class="klasele">
                    <span>{{ $product->name }}</span>
                    <img src="{{ Storage::url($product->image) }}" class="img-responsive center-cropped" >
                    <span>{{ $product->description }}</span>
                    <br>
                    <span>{{ $product->price }} EUR</span>
                </div>
            </a>
        @endforeach
        </div>
        @endif
    </div>
</div>
@endsection

laravel/resources/views/products/product.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-md-12">
        <a href="/meniu"><button>Meniu:</button></a>
        @if (Auth::check())
        <a href="/cart"><button>Cart:</button></a>
        @endif
    </div>
</div>
<div class="row kontaktai">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <table class="table">
                    <tr>
                        <th>ID:</th>
                        <th>Name:</th>
                        <th>Description:</th>
                        <th>Price:</th>
                        <th>Image:</th>
                    </tr>
                    <tr>
                        <td>{{ $product->id }}</td>
                        <td>{{ $product->name }}</td>
                        <td>{{ $product->description }}</td>
                        <td>{{ $product->price }}</td>
                        <td>@if($product->image == null)
                                <span>[Nuotraukos nera]</span>
                            @else
                                <img src="{{ Storage::url($product->image) }}" alt="" style="max-width: 200px;">
                            @endif</td>
                        <td>
                        @if(Auth::check() && Auth::user()->isAdmin())
                        <td>
                            <button>
                                <a href="{{ route('meniu.edit', $product->id) }}">edit</a>
                            </button>
                            <div>
                                {!! Form::open([
                                    'method' => 'DELETE',
                                    'route' => ['meniu.destroy', $product->id]
                                ]) !!}
                                {!! Form::submit('delete', ['class' => 'button']) !!}
                                {!! Form::close() !!}
                            </div>
                            @endif
                            @if (Auth::check())
                                {{ Form::open(array("method"=>"POST", 'route' => 'cart.store')) }}
                                {{ Form::hidden('productId', $product->id) }}
                                {{ Form::text('amount', '1', ['class' => 'form-control']) }}
                                {{ Form::submit('To cart') }}
                                {{ Form::close() }}
                        </td>
                        @endif
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection